### ISSUE TITLE
Release of the sqlalchemyseed v.2.x

### ISSUE THREAD

**Issue by katsu996** [jedymatt/sqlalchemyseed#45]
I would like to use "sqlalchemyseed" with SQLAlchemy v2.
I found the v.2.x branch, is there any plan to release this one?

**Comment by jedymatt** [comment]
Hello, I do still want to release v2 but I have been busy with my thesis and I haven't touched the v2 branch for months. Meanwhile, you can use the v1 which is already stable. I did try to test the sqlalchemyseed right now to see if there are any breaking changes. Thankfully, there are only depreciations. I'll try to release another version 1 which resolves the depreciations. Thanks btw. ☺️

**Comment by katsu996** [comment]
Thanks for releasing version 2.
I always get an error with "add_all" in the seeder when I run it in my local environment.

`AttributeError: 'function' object has no attribute 'add_all'`

The test passes normally, but I don't know why the error occurs.
Do you know how to solve this?

**Comment by jedymatt** [comment]
Can you provide a sample code that produces that error? I'll reproduce the error in my end and see if I can fix this. Thanks.

**Comment by katsu996** [comment]
I am attaching the actual code with some modifications as I am trying to incorporate it into the FastAPI system.


```Python
# test.py

from sqlalchemy import create_engine
from sqlalchemy.orm import Session, sessionmaker
from sqlalchemyseed import Seeder, load_entities_from_json


def get_db():
    DATABASE = "mysql+pymysql://user:password@localhost:3306/db"
    Engine = create_engine(DATABASE, echo=True)
    SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=Engine)

    db = SessionLocal()
    try:
        yield db
    except Exception:
        db.rollback()
    finally:
        db.close()


def import_seed() -> None:
    db: Session = get_db()
    entities: dict = load_entities_from_json("users.json")
    seeder = Seeder(db)
    seeder.seed(entities)

    db.commit()


if __name__ == "__main__":
    import_seed()
```

```JSON
# users.json

{
  "model": "models.Users",
  "data": [
    {
      "name": "John",
      "password": "password01"
    },
    {
      "name": "Smith",
      "password": "password02"
    }
  ]
}
```

**Comment by jedymatt** [comment]
I tried to reproduce the code and I got this error message

```sh
AttributeError: 'generator' object has no attribute 'add_all'
```

The problem lies to the `db: Session = get_db()` which you used to pass in Seeder(db). 

The `get_db` function returns a generator not a Session.  I don't know why you use `yield` instead of `return` but if it is intentional that you're using `yield` then use [`next(get_db())`](https://www.section.io/engineering-education/python-generators/#:~:text=To%20get%20values%20from%20the,loop%20through%20the%20generator%20object.) to return the session value ( you can only call `next` once, or else it will throw an error). 

Here's my solution to the code. Hope it helps ❤️

```python
from sqlalchemy import create_engine
from sqlalchemy.orm import Session, sessionmaker
from sqlalchemyseed import Seeder, load_entities_from_json
import models


def get_db():
    DATABASE = "sqlite://"
    Engine = create_engine(DATABASE, echo=True)
    SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=Engine)

    db = SessionLocal()
    try:
        yield db
    except Exception:
        db.rollback()
    finally:
        db.close()

def create_tables(db: Session):
    models.Base.metadata.create_all(bind=db.bind)

def import_seed(db: Session) -> None:
    entities: dict = load_entities_from_json("users.json")
    seeder = Seeder(db)
    seeder.seed(entities)

    db.commit()


if __name__ == "__main__":
    db = next(get_db()) # use next to get the instance of the Session

    create_tables(db)
    import_seed(db)
    
    print(db.query(models.Users).all())
```

If you are using `return` the instead of `yield` then you don't have to use `next` function as it is used for generator

**Comment by katsu996** [comment]
I used 'next' and it ran fine.
Thank you very much.

The reason I am using 'yield' is because I am using FastAPI's 'Dependency Injection'.
I omitted it because I thought it was unrelated to this event, but that was the problem.
Normally I use 'get_db' as follows.

```Python
# main.py

def get_user(db: Session = Depends(get_db)):
    user = crud_get_user(db)
    return user
````

The return value of 'Depends(get_db)' is 'Session', but there seems to be a problem there.
This may be a problem on the FastAPI side.

**Comment by jedymatt** [comment]
Glad to help. I don't have experience on FastAPI so I can't give you an idea. Just make sure that you are passing an instance of Session when you instantiate the Seeder. If anything goes wrong that might be a bug related to this package, do open another issue. Good luck!

**Comment by jedymatt** [comment]
I tried to create a fastapi project by following [this tutorial](https://fastapi.tiangolo.com/tutorial/sql-databases/#main-fastapi-app) with sqlalchemyseed and fortunately it works.

```py
# The `/seed-users` route in main.py file
@app.get("/seed-users", response_model=list[schemas.User])
def seed_users(db: Session = Depends(get_db)):
    seeder = sqlalchemyseed.Seeder(db)
    entities = sqlalchemyseed.load_entities_from_json('users.json')
    seeder.seed(entities)
    db.commit()

    return seeder.instances
```

```jsonc
// users.json located at the root directory
{
    "model": "models.User",
    "data": [
        {
            "email": "test@example.com",
            "hashed_password": "password"
        },
        {
            "email": "test+1@example.com",
            "hashed_password": "password"
        },
        {
            "email": "test+2@example.com",
            "hashed_password": "password"
        },
        {
            "email": "test+3@example.com",
            "hashed_password": "password"
        },
        {
            "email": "test+4@example.com",
            "hashed_password": "password"
        },
        {
            "email": "test+5@example.com",
            "hashed_password": "password"
        }
    ]
}
```

The response using vscode extension [Thunder Client](https://marketplace.visualstudio.com/items?itemName=rangav.vscode-thunder-client)
![image](https://user-images.githubusercontent.com/54795428/224552673-b608452a-9175-44ca-860c-1d1ccd17e4b6.png)

**Comment by katsu996** [comment]
Thank you for taking the trouble to test with FastAPI.

For some reason it does not work correctly in my environment, so it seems to be related to another problem.
The `next(get_db())` works, so I'll go with that for now.

Thank you very very much.
